{
  "name": "@abba-platforms/cillar",
  "version": "1.0.0",
  "description": "JavaScript utilities for interacting with CillarCoin smart contracts",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/abba-platforms/cillar"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  },
  "author": "Simon Kapenda <skapenda@gmail.com>",
  "license": "MIT"
}
